title: Lopuh's homepage
description: project updates
baseurl: ""  
url: "https://l0puh.github.io"
theme_config:
  dark_mode: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
nav:
  - title: index
    url: /
  - title: about
    url: /about/